from homeassistant.components.sensor import SensorDeviceClass, SensorStateClass

BATTERY_MODULE_SIGNALS_1 = [
    {
        "id": 230320252,
        "name": "[Module 1] No.",
        "custom_name": "[Module 1] No.",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320459,
        "name": "[Module 1] Working Status",
        "custom_name": "[Module 1] Working Status",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320275,
        "name": "[Module 1] SN",
        "custom_name": "[Module 1] SN",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320146,
        "name": "[Module 1] Software Version",
        "custom_name": "[Module 1] Software Version",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320463,
        "name": "[Module 1] SOC",
        "custom_name": "[Module 1] SOC",
        "unit": "%",
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320473,
        "name": "[Module 1] Charge and Discharge Power",
        "custom_name": "[Module 1] Charge and Discharge Power",
        "unit": "kW",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320462,
        "name": "[Module 1] Internal Temperature",
        "custom_name": "[Module 1] Internal Temperature",
        "unit": "°C",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320469,
        "name": "[Module 1] Daily Charge Energy",
        "custom_name": "[Module 1] Daily Charge Energy",
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "id": 230320470,
        "name": "[Module 1] Daily Discharge Energy",
        "custom_name": "[Module 1] Daily Discharge Energy",
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "id": 230320108,
        "name": "[Module 1] Total Discharge Energy",
        "custom_name": "[Module 1] Total Discharge Energy",
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "id": 230320460,
        "name": "[Module 1] Bus Voltage",
        "custom_name": "[Module 1] Bus Voltage",
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320461,
        "name": "[Module 1] Bus Current",
        "custom_name": "[Module 1] Bus Current",
        "unit": "A",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320514,
        "name": "[Module 1] FE Connection",
        "custom_name": "[Module 1] FE Connection",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320107,
        "name": "[Module 1] Total Charge Energy",
        "custom_name": "[Module 1] Total Charge Energy",
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "id": 230320265,
        "name": "[Module 1] Battery Pack 1 No.",
        "custom_name": "[Module 1] Battery Pack 1 No.",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320266,
        "name": "[Module 1] Battery Pack 2 No.",
        "custom_name": "[Module 1] Battery Pack 2 No.",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320267,
        "name": "[Module 1] Battery Pack 3 No.",
        "custom_name": "[Module 1] Battery Pack 3 No.",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320148,
        "name": "[Module 1] Battery Pack 1 Firmware Version",
        "custom_name": "[Module 1] Battery Pack 1 Firmware Version",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320165,
        "name": "[Module 1] Battery Pack 2 Firmware Version",
        "custom_name": "[Module 1] Battery Pack 2 Firmware Version",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320181,
        "name": "[Module 1] Battery Pack 3 Firmware Version",
        "custom_name": "[Module 1] Battery Pack 3 Firmware Version",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320147,
        "name": "[Module 1] Battery Pack 1 SN",
        "custom_name": "[Module 1] Battery Pack 1 SN",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320164,
        "name": "[Module 1] Battery Pack 2 SN",
        "custom_name": "[Module 1] Battery Pack 2 SN",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320180,
        "name": "[Module 1] Battery Pack 3 SN",
        "custom_name": "[Module 1] Battery Pack 3 SN",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320151,
        "name": "[Module 1] Battery Pack 1 Operating Status",
        "custom_name": "[Module 1] Battery Pack 1 Operating Status",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320168,
        "name": "[Module 1] Battery Pack 2 Operating Status",
        "custom_name": "[Module 1] Battery Pack 2 Operating Status",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320184,
        "name": "[Module 1] Battery Pack 3 Operating Status",
        "custom_name": "[Module 1] Battery Pack 3 Operating Status",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320159,
        "name": "[Module 1] Battery Pack 1 Voltage",
        "custom_name": "[Module 1] Battery Pack 1 Voltage",
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320174,
        "name": "[Module 1] Battery Pack 2 Voltage",
        "custom_name": "[Module 1] Battery Pack 2 Voltage",
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320190,
        "name": "[Module 1] Battery Pack 3 Voltage",
        "custom_name": "[Module 1] Battery Pack 3 Voltage",
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320158,
        "name": "[Module 1] Battery Pack 1 Charge/Discharge Power",
        "custom_name": "[Module 1] Battery Pack 1 Charge/Discharge Power",
        "unit": "kW",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320173,
        "name": "[Module 1] Battery Pack 2 Charge/Discharge Power",
        "custom_name": "[Module 1] Battery Pack 2 Charge/Discharge Power",
        "unit": "kW",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320189,
        "name": "[Module 1] Battery Pack 3 Charge/Discharge Power",
        "custom_name": "[Module 1] Battery Pack 3 Charge/Discharge Power",
        "unit": "kW",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320446,
        "name": "[Module 1] Battery Pack 1 Maximum Temperature",
        "custom_name": "[Module 1] Battery Pack 1 Maximum Temperature",
        "unit": "°C",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320448,
        "name": "[Module 1] Battery Pack 2 Maximum Temperature",
        "custom_name": "[Module 1] Battery Pack 2 Maximum Temperature",
        "unit": "°C",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320450,
        "name": "[Module 1] Battery Pack 3 Maximum Temperature",
        "custom_name": "[Module 1] Battery Pack 3 Maximum Temperature",
        "unit": "°C",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320447,
        "name": "[Module 1] Battery Pack 1 Minimum Temperature",
        "custom_name": "[Module 1] Battery Pack 1 Minimum Temperature",
        "unit": "°C",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320449,
        "name": "[Module 1] Battery Pack 2 Minimum Temperature",
        "custom_name": "[Module 1] Battery Pack 2 Minimum Temperature",
        "unit": "°C",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320451,
        "name": "[Module 1] Battery Pack 3 Minimum Temperature",
        "custom_name": "[Module 1] Battery Pack 3 Minimum Temperature",
        "unit": "°C",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320152,
        "name": "[Module 1] Battery Pack 1 SOC",
        "custom_name": "[Module 1] Battery Pack 1 SOC",
        "unit": "%",
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320169,
        "name": "[Module 1] Battery Pack 2 SOC",
        "custom_name": "[Module 1] Battery Pack 2 SOC",
        "unit": "%",
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320185,
        "name": "[Module 1] Battery Pack 3 SOC",
        "custom_name": "[Module 1] Battery Pack 3 SOC",
        "unit": "%",
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320163,
        "name": "[Module 1] Battery Pack 1 Total Discharge Energy",
        "custom_name": "[Module 1] Battery Pack 1 Total Discharge Energy",
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "id": 230320179,
        "name": "[Module 1] Battery Pack 2 Total Discharge Energy",
        "custom_name": "[Module 1] Battery Pack 2 Total Discharge Energy",
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "id": 230320194,
        "name": "[Module 1] Battery Pack 3 Total Discharge Energy",
        "custom_name": "[Module 1] Battery Pack 3 Total Discharge Energy",
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "id": 230320492,
        "name": "[Module 1] Battery Pack 1 Battery Health Check",
        "custom_name": "[Module 1] Battery Pack 1 Battery Health Check",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320493,
        "name": "[Module 1] Battery Pack 2 Battery Health Check",
        "custom_name": "[Module 1] Battery Pack 2 Battery Health Check",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320494,
        "name": "[Module 1] Battery Pack 3 Battery Health Check",
        "custom_name": "[Module 1] Battery Pack 3 Battery Health Check",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320498,
        "name": "[Module 1] Battery Pack 1 Heating Status",
        "custom_name": "[Module 1] Battery Pack 1 Heating Status",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320499,
        "name": "[Module 1] Battery Pack 2 Heating Status",
        "custom_name": "[Module 1] Battery Pack 2 Heating Status",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320500,
        "name": "[Module 1] Battery Pack 3 Heating Status",
        "custom_name": "[Module 1] Battery Pack 3 Heating Status",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
]

BATTERY_MODULE_SIGNALS_2 = [
    {
        "id": 230320253,
        "name": "[Module 2] No.",
        "custom_name": "[Module 2] No.",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320464,
        "name": "[Module 2] Working Status",
        "custom_name": "[Module 2] Working Status",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320276,
        "name": "[Module 2] SN",
        "custom_name": "[Module 2] SN",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320145,
        "name": "[Module 2] Software Version",
        "custom_name": "[Module 2] Software Version",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320468,
        "name": "[Module 2] SOC",
        "custom_name": "[Module 2] SOC",
        "unit": "%",
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320474,
        "name": "[Module 2] Charge and Discharge Power",
        "custom_name": "[Module 2] Charge and Discharge Power",
        "unit": "kW",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320467,
        "name": "[Module 2] Internal Temperature",
        "custom_name": "[Module 2] Internal Temperature",
        "unit": "°C",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320471,
        "name": "[Module 2] Daily Charge Energy",
        "custom_name": "[Module 2] Daily Charge Energy",
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "id": 230320472,
        "name": "[Module 2] Daily Discharge Energy",
        "custom_name": "[Module 2] Daily Discharge Energy",
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "id": 230320115,
        "name": "[Module 2] Total Discharge Energy",
        "custom_name": "[Module 2] Total Discharge Energy",
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "id": 230320465,
        "name": "[Module 2] Bus Voltage",
        "custom_name": "[Module 2] Bus Voltage",
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320466,
        "name": "[Module 2] Bus Current",
        "custom_name": "[Module 2] Bus Current",
        "unit": "A",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320515,
        "name": "[Module 2] FE Connection",
        "custom_name": "[Module 2] FE Connection",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320114,
        "name": "[Module 2] Total Charge Energy",
        "custom_name": "[Module 2] Total Charge Energy",
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "id": 230320268,
        "name": "[Module 2] Battery Pack 1 No.",
        "custom_name": "[Module 2] Battery Pack 1 No.",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320269,
        "name": "[Module 2] Battery Pack 2 No.",
        "custom_name": "[Module 2] Battery Pack 2 No.",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320270,
        "name": "[Module 2] Battery Pack 3 No.",
        "custom_name": "[Module 2] Battery Pack 3 No.",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320196,
        "name": "[Module 2] Battery Pack 1 Firmware Version",
        "custom_name": "[Module 2] Battery Pack 1 Firmware Version",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320211,
        "name": "[Module 2] Battery Pack 2 Firmware Version",
        "custom_name": "[Module 2] Battery Pack 2 Firmware Version",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320226,
        "name": "[Module 2] Battery Pack 3 Firmware Version",
        "custom_name": "[Module 2] Battery Pack 3 Firmware Version",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320195,
        "name": "[Module 2] Battery Pack 1 SN",
        "custom_name": "[Module 2] Battery Pack 1 SN",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320210,
        "name": "[Module 2] Battery Pack 2 SN",
        "custom_name": "[Module 2] Battery Pack 2 SN",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320225,
        "name": "[Module 2] Battery Pack 3 SN",
        "custom_name": "[Module 2] Battery Pack 3 SN",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320199,
        "name": "[Module 2] Battery Pack 1 Operating Status",
        "custom_name": "[Module 2] Battery Pack 1 Operating Status",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320214,
        "name": "[Module 2] Battery Pack 2 Operating Status",
        "custom_name": "[Module 2] Battery Pack 2 Operating Status",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320229,
        "name": "[Module 2] Battery Pack 3 Operating Status",
        "custom_name": "[Module 2] Battery Pack 3 Operating Status",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320205,
        "name": "[Module 2] Battery Pack 1 Voltage",
        "custom_name": "[Module 2] Battery Pack 1 Voltage",
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320220,
        "name": "[Module 2] Battery Pack 2 Voltage",
        "custom_name": "[Module 2] Battery Pack 2 Voltage",
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320235,
        "name": "[Module 2] Battery Pack 3 Voltage",
        "custom_name": "[Module 2] Battery Pack 3 Voltage",
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320204,
        "name": "[Module 2] Battery Pack 1 Charge/Discharge Power",
        "custom_name": "[Module 2] Battery Pack 1 Charge/Discharge Power",
        "unit": "kW",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320219,
        "name": "[Module 2] Battery Pack 2 Charge/Discharge Power",
        "custom_name": "[Module 2] Battery Pack 2 Charge/Discharge Power",
        "unit": "kW",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320234,
        "name": "[Module 2] Battery Pack 3 Charge/Discharge Power",
        "custom_name": "[Module 2] Battery Pack 3 Charge/Discharge Power",
        "unit": "kW",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320452,
        "name": "[Module 2] Battery Pack 1 Maximum Temperature",
        "custom_name": "[Module 2] Battery Pack 1 Maximum Temperature",
        "unit": "°C",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320454,
        "name": "[Module 2] Battery Pack 2 Maximum Temperature",
        "custom_name": "[Module 2] Battery Pack 2 Maximum Temperature",
        "unit": "°C",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320456,
        "name": "[Module 2] Battery Pack 3 Maximum Temperature",
        "custom_name": "[Module 2] Battery Pack 3 Maximum Temperature",
        "unit": "°C",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320453,
        "name": "[Module 2] Battery Pack 1 Minimum Temperature",
        "custom_name": "[Module 2] Battery Pack 1 Minimum Temperature",
        "unit": "°C",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320455,
        "name": "[Module 2] Battery Pack 2 Minimum Temperature",
        "custom_name": "[Module 2] Battery Pack 2 Minimum Temperature",
        "unit": "°C",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320457,
        "name": "[Module 2] Battery Pack 3 Minimum Temperature",
        "custom_name": "[Module 2] Battery Pack 3 Minimum Temperature",
        "unit": "°C",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320200,
        "name": "[Module 2] Battery Pack 1 SOC",
        "custom_name": "[Module 2] Battery Pack 1 SOC",
        "unit": "%",
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320215,
        "name": "[Module 2] Battery Pack 2 SOC",
        "custom_name": "[Module 2] Battery Pack 2 SOC",
        "unit": "%",
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320230,
        "name": "[Module 2] Battery Pack 3 SOC",
        "custom_name": "[Module 2] Battery Pack 3 SOC",
        "unit": "%",
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320209,
        "name": "[Module 2] Battery Pack 1 Total Discharge Energy",
        "custom_name": "[Module 2] Battery Pack 1 Total Discharge Energy",
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "id": 230320224,
        "name": "[Module 2] Battery Pack 2 Total Discharge Energy",
        "custom_name": "[Module 2] Battery Pack 2 Total Discharge Energy",
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "id": 230320239,
        "name": "[Module 2] Battery Pack 3 Total Discharge Energy",
        "custom_name": "[Module 2] Battery Pack 3 Total Discharge Energy",
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "id": 230320495,
        "name": "[Module 2] Battery Pack 1 Battery Health Check",
        "custom_name": "[Module 2] Battery Pack 1 Battery Health Check",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320496,
        "name": "[Module 2] Battery Pack 2 Battery Health Check",
        "custom_name": "[Module 2] Battery Pack 2 Battery Health Check",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320497,
        "name": "[Module 2] Battery Pack 3 Battery Health Check",
        "custom_name": "[Module 2] Battery Pack 3 Battery Health Check",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320501,
        "name": "[Module 2] Battery Pack 1 Heating Status",
        "custom_name": "[Module 2] Battery Pack 1 Heating Status",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320502,
        "name": "[Module 2] Battery Pack 2 Heating Status",
        "custom_name": "[Module 2] Battery Pack 2 Heating Status",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
    {
        "id": 230320503,
        "name": "[Module 2] Battery Pack 3 Heating Status",
        "custom_name": "[Module 2] Battery Pack 3 Heating Status",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
    },
]

BATTERY_MODULE_SIGNALS_3 = [
    {
        "id": 230320640,
        "name": "[Module 3] No.",
        "custom_name": "[Module 3] No.",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
    {
        "id": 230320526,
        "name": "[Module 3] Working Status",
        "custom_name": "[Module 3] Working Status",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
    {
        "id": 230320536,
        "name": "[Module 3] SN",
        "custom_name": "[Module 3] SN",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
    {
        "id": 230320542,
        "name": "[Module 3] Software Version",
        "custom_name": "[Module 3] Software Version",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
    {
        "id": 230320529,
        "name": "[Module 3] SOC",
        "custom_name": "[Module 3] SOC",
        "unit": "%",
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320527,
        "name": "[Module 3] Charge and Discharge Power",
        "custom_name": "[Module 3] Charge and Discharge Power",
        "unit": "kW",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320535,
        "name": "[Module 3] Internal Temperature",
        "custom_name": "[Module 3] Internal Temperature",
        "unit": "°C",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320532,
        "name": "[Module 3] Daily Charge Energy",
        "custom_name": "[Module 3] Daily Charge Energy",
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "id": 230320533,
        "name": "[Module 3] Daily Discharge Energy",
        "custom_name": "[Module 3] Daily Discharge Energy",
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "id": 230320539,
        "name": "[Module 3] Total Discharge Energy",
        "custom_name": "[Module 3] Total Discharge Energy",
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "id": 230320528,
        "name": "[Module 3] Bus Voltage",
        "custom_name": "[Module 3] Bus Voltage",
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320534,
        "name": "[Module 3] Bus Current",
        "custom_name": "[Module 3] Bus Current",
        "unit": "A",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320516,
        "name": "[Module 3] FE Connection",
        "custom_name": "[Module 3] FE Connection",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
    {
        "id": 230320538,
        "name": "[Module 3] Total Charge Energy",
        "custom_name": "[Module 3] Total Charge Energy",
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "id": 230320646,
        "name": "[Module 3] Battery Pack 1 No.",
        "custom_name": "[Module 3] Battery Pack 1 No.",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
    {
        "id": 230320647,
        "name": "[Module 3] Battery Pack 2 No.",
        "custom_name": "[Module 3] Battery Pack 2 No.",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
    {
        "id": 230320648,
        "name": "[Module 3] Battery Pack 3 No.",
        "custom_name": "[Module 3] Battery Pack 3 No.",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
    {
        "id": 230320544,
        "name": "[Module 3] Battery Pack 1 Firmware Version",
        "custom_name": "[Module 3] Battery Pack 1 Firmware Version",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
    {
        "id": 230320555,
        "name": "[Module 3] Battery Pack 2 Firmware Version",
        "custom_name": "[Module 3] Battery Pack 2 Firmware Version",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
    {
        "id": 230320566,
        "name": "[Module 3] Battery Pack 3 Firmware Version",
        "custom_name": "[Module 3] Battery Pack 3 Firmware Version",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
    {
        "id": 230320543,
        "name": "[Module 3] Battery Pack 1 SN",
        "custom_name": "[Module 3] Battery Pack 1 SN",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
    {
        "id": 230320554,
        "name": "[Module 3] Battery Pack 2 SN",
        "custom_name": "[Module 3] Battery Pack 2 SN",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
    {
        "id": 230320565,
        "name": "[Module 3] Battery Pack 3 SN",
        "custom_name": "[Module 3] Battery Pack 3 SN",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
    {
        "id": 230320545,
        "name": "[Module 3] Battery Pack 1 Operating Status",
        "custom_name": "[Module 3] Battery Pack 1 Operating Status",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
    {
        "id": 230320556,
        "name": "[Module 3] Battery Pack 2 Operating Status",
        "custom_name": "[Module 3] Battery Pack 2 Operating Status",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
    {
        "id": 230320567,
        "name": "[Module 3] Battery Pack 3 Operating Status",
        "custom_name": "[Module 3] Battery Pack 3 Operating Status",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
    {
        "id": 230320549,
        "name": "[Module 3] Battery Pack 1 Voltage",
        "custom_name": "[Module 3] Battery Pack 1 Voltage",
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320560,
        "name": "[Module 3] Battery Pack 2 Voltage",
        "custom_name": "[Module 3] Battery Pack 2 Voltage",
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320571,
        "name": "[Module 3] Battery Pack 3 Voltage",
        "custom_name": "[Module 3] Battery Pack 3 Voltage",
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320548,
        "name": "[Module 3] Battery Pack 1 Charge/Discharge Power",
        "custom_name": "[Module 3] Battery Pack 1 Charge/Discharge Power",
        "unit": "kW",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320559,
        "name": "[Module 3] Battery Pack 2 Charge/Discharge Power",
        "custom_name": "[Module 3] Battery Pack 2 Charge/Discharge Power",
        "unit": "kW",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320570,
        "name": "[Module 3] Battery Pack 3 Charge/Discharge Power",
        "custom_name": "[Module 3] Battery Pack 3 Charge/Discharge Power",
        "unit": "kW",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320576,
        "name": "[Module 3] Battery Pack 1 Maximum Temperature",
        "custom_name": "[Module 3] Battery Pack 1 Maximum Temperature",
        "unit": "°C",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320578,
        "name": "[Module 3] Battery Pack 2 Maximum Temperature",
        "custom_name": "[Module 3] Battery Pack 2 Maximum Temperature",
        "unit": "°C",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320580,
        "name": "[Module 3] Battery Pack 3 Maximum Temperature",
        "custom_name": "[Module 3] Battery Pack 3 Maximum Temperature",
        "unit": "°C",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320577,
        "name": "[Module 3] Battery Pack 1 Minimum Temperature",
        "custom_name": "[Module 3] Battery Pack 1 Minimum Temperature",
        "unit": "°C",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320579,
        "name": "[Module 3] Battery Pack 2 Minimum Temperature",
        "custom_name": "[Module 3] Battery Pack 2 Minimum Temperature",
        "unit": "°C",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320581,
        "name": "[Module 3] Battery Pack 3 Minimum Temperature",
        "custom_name": "[Module 3] Battery Pack 3 Minimum Temperature",
        "unit": "°C",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320546,
        "name": "[Module 3] Battery Pack 1 Capacity",
        "custom_name": "[Module 3] Battery Pack 1 Capacity",
        "unit": "Ah",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320557,
        "name": "[Module 3] Battery Pack 2 Capacity",
        "custom_name": "[Module 3] Battery Pack 2 Capacity",
        "unit": "Ah",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320568,
        "name": "[Module 3] Battery Pack 3 Capacity",
        "custom_name": "[Module 3] Battery Pack 3 Capacity",
        "unit": "Ah",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320552,
        "name": "[Module 3] Battery Pack 1 Current",
        "custom_name": "[Module 3] Battery Pack 1 Current",
        "unit": "A",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320563,
        "name": "[Module 3] Battery Pack 2 Current",
        "custom_name": "[Module 3] Battery Pack 2 Current",
        "unit": "A",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320574,
        "name": "[Module 3] Battery Pack 3 Current",
        "custom_name": "[Module 3] Battery Pack 3 Current",
        "unit": "A",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320553,
        "name": "[Module 3] Battery Pack 1 SOC",
        "custom_name": "[Module 3] Battery Pack 1 SOC",
        "unit": "%",
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320564,
        "name": "[Module 3] Battery Pack 2 SOC",
        "custom_name": "[Module 3] Battery Pack 2 SOC",
        "unit": "%",
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320575,
        "name": "[Module 3] Battery Pack 3 SOC",
        "custom_name": "[Module 3] Battery Pack 3 SOC",
        "unit": "%",
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320504,
        "name": "[Module 3] Battery Pack 1 High Voltage Fuse Status",
        "custom_name": "[Module 3] Battery Pack 1 High Voltage Fuse Status",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
    {
        "id": 230320505,
        "name": "[Module 3] Battery Pack 2 High Voltage Fuse Status",
        "custom_name": "[Module 3] Battery Pack 2 High Voltage Fuse Status",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
    {
        "id": 230320506,
        "name": "[Module 3] Battery Pack 3 High Voltage Fuse Status",
        "custom_name": "[Module 3] Battery Pack 3 High Voltage Fuse Status",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
]

BATTERY_MODULE_SIGNALS_4 = [
    {
        "id": 230320641,
        "name": "[Module 4] No.",
        "custom_name": "[Module 4] No.",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
    {
        "id": 230320583,
        "name": "[Module 4] Working Status",
        "custom_name": "[Module 4] Working Status",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
    {
        "id": 230320593,
        "name": "[Module 4] SN",
        "custom_name": "[Module 4] SN",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
    {
        "id": 230320599,
        "name": "[Module 4] Software Version",
        "custom_name": "[Module 4] Software Version",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
    {
        "id": 230320586,
        "name": "[Module 4] SOC",
        "custom_name": "[Module 4] SOC",
        "unit": "%",
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320584,
        "name": "[Module 4] Charge and Discharge Power",
        "custom_name": "[Module 4] Charge and Discharge Power",
        "unit": "kW",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320592,
        "name": "[Module 4] Internal Temperature",
        "custom_name": "[Module 4] Internal Temperature",
        "unit": "°C",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320589,
        "name": "[Module 4] Daily Charge Energy",
        "custom_name": "[Module 4] Daily Charge Energy",
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "id": 230320590,
        "name": "[Module 4] Daily Discharge Energy",
        "custom_name": "[Module 4] Daily Discharge Energy",
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "id": 230320596,
        "name": "[Module 4] Total Discharge Energy",
        "custom_name": "[Module 4] Total Discharge Energy",
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "id": 230320585,
        "name": "[Module 4] Bus Voltage",
        "custom_name": "[Module 4] Bus Voltage",
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320591,
        "name": "[Module 4] Bus Current",
        "custom_name": "[Module 4] Bus Current",
        "unit": "A",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320517,
        "name": "[Module 4] FE Connection",
        "custom_name": "[Module 4] FE Connection",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
    {
        "id": 230320595,
        "name": "[Module 4] Total Charge Energy",
        "custom_name": "[Module 4] Total Charge Energy",
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "id": 230320649,
        "name": "[Module 4] Battery Pack 1 No.",
        "custom_name": "[Module 4] Battery Pack 1 No.",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
    {
        "id": 230320650,
        "name": "[Module 4] Battery Pack 2 No.",
        "custom_name": "[Module 4] Battery Pack 2 No.",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
    {
        "id": 230320651,
        "name": "[Module 4] Battery Pack 3 No.",
        "custom_name": "[Module 4] Battery Pack 3 No.",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
    {
        "id": 230320601,
        "name": "[Module 4] Battery Pack 1 Firmware Version",
        "custom_name": "[Module 4] Battery Pack 1 Firmware Version",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
    {
        "id": 230320612,
        "name": "[Module 4] Battery Pack 2 Firmware Version",
        "custom_name": "[Module 4] Battery Pack 2 Firmware Version",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
    {
        "id": 230320623,
        "name": "[Module 4] Battery Pack 3 Firmware Version",
        "custom_name": "[Module 4] Battery Pack 3 Firmware Version",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
    {
        "id": 230320600,
        "name": "[Module 4] Battery Pack 1 SN",
        "custom_name": "[Module 4] Battery Pack 1 SN",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
    {
        "id": 230320611,
        "name": "[Module 4] Battery Pack 2 SN",
        "custom_name": "[Module 4] Battery Pack 2 SN",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
    {
        "id": 230320622,
        "name": "[Module 4] Battery Pack 3 SN",
        "custom_name": "[Module 4] Battery Pack 3 SN",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
    {
        "id": 230320602,
        "name": "[Module 4] Battery Pack 1 Operating Status",
        "custom_name": "[Module 4] Battery Pack 1 Operating Status",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
    {
        "id": 230320613,
        "name": "[Module 4] Battery Pack 2 Operating Status",
        "custom_name": "[Module 4] Battery Pack 2 Operating Status",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
    {
        "id": 230320624,
        "name": "[Module 4] Battery Pack 3 Operating Status",
        "custom_name": "[Module 4] Battery Pack 3 Operating Status",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
    {
        "id": 230320606,
        "name": "[Module 4] Battery Pack 1 Voltage",
        "custom_name": "[Module 4] Battery Pack 1 Voltage",
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320617,
        "name": "[Module 4] Battery Pack 2 Voltage",
        "custom_name": "[Module 4] Battery Pack 2 Voltage",
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320628,
        "name": "[Module 4] Battery Pack 3 Voltage",
        "custom_name": "[Module 4] Battery Pack 3 Voltage",
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320605,
        "name": "[Module 4] Battery Pack 1 Charge/Discharge Power",
        "custom_name": "[Module 4] Battery Pack 1 Charge/Discharge Power",
        "unit": "kW",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320616,
        "name": "[Module 4] Battery Pack 2 Charge/Discharge Power",
        "custom_name": "[Module 4] Battery Pack 2 Charge/Discharge Power",
        "unit": "kW",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320627,
        "name": "[Module 4] Battery Pack 3 Charge/Discharge Power",
        "custom_name": "[Module 4] Battery Pack 3 Charge/Discharge Power",
        "unit": "kW",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320633,
        "name": "[Module 4] Battery Pack 1 Maximum Temperature",
        "custom_name": "[Module 4] Battery Pack 1 Maximum Temperature",
        "unit": "°C",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320635,
        "name": "[Module 4] Battery Pack 2 Maximum Temperature",
        "custom_name": "[Module 4] Battery Pack 2 Maximum Temperature",
        "unit": "°C",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320637,
        "name": "[Module 4] Battery Pack 3 Maximum Temperature",
        "custom_name": "[Module 4] Battery Pack 3 Maximum Temperature",
        "unit": "°C",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320634,
        "name": "[Module 4] Battery Pack 1 Minimum Temperature",
        "custom_name": "[Module 4] Battery Pack 1 Minimum Temperature",
        "unit": "°C",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320636,
        "name": "[Module 4] Battery Pack 2 Minimum Temperature",
        "custom_name": "[Module 4] Battery Pack 2 Minimum Temperature",
        "unit": "°C",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320638,
        "name": "[Module 4] Battery Pack 3 Minimum Temperature",
        "custom_name": "[Module 4] Battery Pack 3 Minimum Temperature",
        "unit": "°C",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320603,
        "name": "[Module 4] Battery Pack 1 Capacity",
        "custom_name": "[Module 4] Battery Pack 1 Capacity",
        "unit": "Ah",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320614,
        "name": "[Module 4] Battery Pack 2 Capacity",
        "custom_name": "[Module 4] Battery Pack 2 Capacity",
        "unit": "Ah",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320625,
        "name": "[Module 4] Battery Pack 3 Capacity",
        "custom_name": "[Module 4] Battery Pack 3 Capacity",
        "unit": "Ah",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320609,
        "name": "[Module 4] Battery Pack 1 Current",
        "custom_name": "[Module 4] Battery Pack 1 Current",
        "unit": "A",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320620,
        "name": "[Module 4] Battery Pack 2 Current",
        "custom_name": "[Module 4] Battery Pack 2 Current",
        "unit": "A",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320631,
        "name": "[Module 4] Battery Pack 3 Current",
        "custom_name": "[Module 4] Battery Pack 3 Current",
        "unit": "A",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320610,
        "name": "[Module 4] Battery Pack 1 SOC",
        "custom_name": "[Module 4] Battery Pack 1 SOC",
        "unit": "%",
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320621,
        "name": "[Module 4] Battery Pack 2 SOC",
        "custom_name": "[Module 4] Battery Pack 2 SOC",
        "unit": "%",
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320632,
        "name": "[Module 4] Battery Pack 3 SOC",
        "custom_name": "[Module 4] Battery Pack 3 SOC",
        "unit": "%",
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230320507,
        "name": "[Module 4] Battery Pack 1 High Voltage Fuse Status",
        "custom_name": "[Module 4] Battery Pack 1 High Voltage Fuse Status",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
    {
        "id": 230320508,
        "name": "[Module 4] Battery Pack 2 High Voltage Fuse Status",
        "custom_name": "[Module 4] Battery Pack 2 High Voltage Fuse Status",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
    {
        "id": 230320509,
        "name": "[Module 4] Battery Pack 3 High Voltage Fuse Status",
        "custom_name": "[Module 4] Battery Pack 3 High Voltage Fuse Status",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
        "state_class": None,
    },
]

BATTERY_STATUS_SIGNALS = [
    {
        "id": 10003,
        "name": "Battery operating status",
        "custom_name": "Operating Status",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
    },
    {
        "id": 10008,
        "name": "Charge/Discharge mode",
        "custom_name": "Charge/Discharge Mode",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
    },
    {
        "id": 10013,
        "name": "Rated capacity",
        "custom_name": "Rated Capacity",
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": None,
    },
    {
        "id": 10015,
        "name": "Backup time",
        "custom_name": "Backup Time",
        "unit": "min",
        "device_class": SensorDeviceClass.DURATION,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 10001,
        "name": "Energy charged today",
        "custom_name": "Energy Charged Today",
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "id": 10002,
        "name": "Energy discharged today",
        "custom_name": "Energy Discharged Today",
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "id": 10004,
        "name": "Charge/Discharge power",
        "custom_name": "Charge/Discharge Power",
        "unit": "kW",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 10005,
        "name": "Bus voltage",
        "custom_name": "Bus Voltage",
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 10006,
        "name": "SOC",
        "custom_name": "State of Charge",
        "unit": "%",
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
    },
]

MODULE_SIGNAL_MAP = {
    "1": BATTERY_MODULE_SIGNALS_1,
    "2": BATTERY_MODULE_SIGNALS_2,
    "3": BATTERY_MODULE_SIGNALS_3,
    "4": BATTERY_MODULE_SIGNALS_4,
}
