from homeassistant.components.sensor import SensorDeviceClass, SensorStateClass

EMMA_SIGNALS = [
    {
        "id": 11115,
        "name": "Forward active energy",
        "unit": "kWh",
        "custom_name": "Forward Active Energy",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "id": 11116,
        "name": "Reverse active energy",
        "unit": "kWh",
        "custom_name": "Reverse Active Energy",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "id": 11208,
        "name": "Reactive power",
        "unit": "kvar",
        "custom_name": "Reactive Power",
        "device_class": SensorDeviceClass.REACTIVE_POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 11207,
        "name": "Active power",
        "unit": "kW",
        "custom_name": "Active Power",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 10014,
        "name": "Power factor",
        "custom_name": "Power Factor",
        "unit": None,
        "device_class": SensorDeviceClass.POWER_FACTOR,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 11209,
        "name": "Active power Pa",
        "unit": "kW",
        "custom_name": "Active Power Pa",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 11210,
        "name": "Active power Pb",
        "unit": "kW",
        "custom_name": "Active Power Pb",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 11211,
        "name": "Active power Pc",
        "unit": "kW",
        "custom_name": "Active Power Pc",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 11204,
        "name": "Phase A voltage",
        "unit": "V",
        "custom_name": "Phase A Voltage",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 11205,
        "name": "Phase B voltage",
        "unit": "V",
        "custom_name": "Phase B Voltage",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 11206,
        "name": "Phase C voltage",
        "unit": "V",
        "custom_name": "Phase C Voltage",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 10009,
        "name": "Phase A current",
        "unit": "A",
        "custom_name": "Phase A Current",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 10010,
        "name": "Phase B current",
        "unit": "A",
        "custom_name": "Phase B Current",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 10011,
        "name": "Phase C current",
        "unit": "A",
        "custom_name": "Phase C Current",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
    },
]
