from homeassistant.components.sensor import SensorDeviceClass, SensorStateClass

POWER_SENSOR_SIGNALS = [
    {
        "id": 10001,
        "name": "Meter status",
        "custom_name": "Meter Status",
        "device_class": SensorDeviceClass.ENUM,
        "unit": None,
    },
    {
        "id": 10008,
        "name": "Positive active energy",
        "unit": "kWh",
        "custom_name": "Positive Active Energy",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "id": 10009,
        "name": "Negative active energy",
        "unit": "kWh",
        "custom_name": "Negative Active Energy",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "id": 10005,
        "name": "Reactive power",
        "unit": "var",
        "custom_name": "Reactive Power",
        "device_class": SensorDeviceClass.REACTIVE_POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 10004,
        "name": "Active power",
        "unit": "W",
        "custom_name": "Active Power",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 10006,
        "name": "Power factor",
        "custom_name": "Power Factor",
        "unit": None,
        "device_class": SensorDeviceClass.POWER_FACTOR,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 10019,
        "name": "Phase A active power",
        "unit": "W",
        "custom_name": "Phase A Active Power",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 10020,
        "name": "Phase B active power",
        "unit": "W",
        "custom_name": "Phase B Active Power",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 10021,
        "name": "Phase C active power",
        "unit": "W",
        "custom_name": "Phase C Active Power",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 10002,
        "name": "Phase A voltage",
        "unit": "V",
        "custom_name": "Phase A Voltage",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 10010,
        "name": "Phase B voltage",
        "unit": "V",
        "custom_name": "Phase B Voltage",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 10011,
        "name": "Phase C voltage",
        "unit": "V",
        "custom_name": "Phase C Voltage",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 10003,
        "name": "Phase A current",
        "unit": "A",
        "custom_name": "Phase A Current",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 10012,
        "name": "Phase B current",
        "unit": "A",
        "custom_name": "Phase B Current",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 10013,
        "name": "Phase C current",
        "unit": "A",
        "custom_name": "Phase C Current",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 10007,
        "name": "Grid frequency",
        "unit": "Hz",
        "custom_name": "Grid Frequency",
        "device_class": SensorDeviceClass.FREQUENCY,
        "state_class": SensorStateClass.MEASUREMENT,
    },
]


EMMA_A02_SIGNALS = [
    {
        "id": 11115,
        "name": "Forward active energy",
        "custom_name": "Forward Active Energy",
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "id": 11116,
        "name": "Reverse active energy",
        "custom_name": "Reverse Active Energy",
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "id": 11208,
        "name": "Reactive power",
        "custom_name": "Reactive Power",
        "unit": "kvar",
        "device_class": SensorDeviceClass.REACTIVE_POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 11207,
        "name": "Active power",
        "custom_name": "Active Power",
        "unit": "kW",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 10014,
        "name": "Power factor",
        "custom_name": "Power Factor",
        "unit": None,
        "device_class": SensorDeviceClass.POWER_FACTOR,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 11209,
        "name": "Active power Pa",
        "custom_name": "Phase A Active Power",
        "unit": "kW",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 11210,
        "name": "Active power Pb",
        "custom_name": "Phase B Active Power",
        "unit": "kW",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 11211,
        "name": "Active power Pc",
        "custom_name": "Phase C Active Power",
        "unit": "kW",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 11204,
        "name": "Phase A voltage",
        "custom_name": "Phase A Voltage",
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 11205,
        "name": "Phase B voltage",
        "custom_name": "Phase B Voltage",
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 11206,
        "name": "Phase C voltage",
        "custom_name": "Phase C Voltage",
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 10009,
        "name": "Phase A current",
        "custom_name": "Phase A Current",
        "unit": "A",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 10010,
        "name": "Phase B current",
        "custom_name": "Phase B Current",
        "unit": "A",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 10011,
        "name": "Phase C current",
        "custom_name": "Phase C Current",
        "unit": "A",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 230700283,
        "name": "RS485-2 port mode",
        "custom_name": "RS485-2 Port Mode",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
    },
    {
        "id": 15101,
        "name": "WiFi Signal strength",
        "custom_name": "WiFi Signal Strength",
        "unit": "dBm",  # May be incorrect
        "device_class": SensorDeviceClass.SIGNAL_STRENGTH,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 15102,
        "name": "Signal strength",
        "custom_name": "Signal Strength",
        "unit": "dBm",
        "device_class": SensorDeviceClass.SIGNAL_STRENGTH,
        "state_class": SensorStateClass.MEASUREMENT,
    },
]

DTSU666_FE_SIGNALS = [
    {
        "id": 2101249,
        "name": "Communication Status",
        "custom_name": "Communication Status",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
    },
    {
        "id": 2101252,
        "name": "AB line voltage",
        "custom_name": "AB Line Voltage",
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 2101253,
        "name": "BC line voltage",
        "custom_name": "BC Line Voltage",
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 2101254,
        "name": "CA line voltage",
        "custom_name": "CA Line Voltage",
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 2101256,
        "name": "Phase A voltage",
        "custom_name": "Phase A Voltage",
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 2101257,
        "name": "Phase B voltage",
        "custom_name": "Phase B Voltage",
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 2101264,
        "name": "Phase C voltage",
        "custom_name": "Phase C Voltage",
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 2101268,
        "name": "Phase A current",
        "custom_name": "Phase A Current",
        "unit": "A",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 2101269,
        "name": "Phase B current",
        "custom_name": "Phase B Current",
        "unit": "A",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 2101270,
        "name": "Phase C current",
        "custom_name": "Phase C Current",
        "unit": "A",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 2101271,
        "name": "Active power",
        "custom_name": "Active Power",
        "unit": "kW",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 2101272,
        "name": "Reactive power",
        "custom_name": "Reactive Power",
        "unit": "kVar",
        "device_class": SensorDeviceClass.REACTIVE_POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 2101280,
        "name": "Power factor",
        "custom_name": "Power Factor",
        "unit": None,
        "device_class": SensorDeviceClass.POWER_FACTOR,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 2101281,
        "name": "Phase A active power",
        "custom_name": "Phase A Active Power",
        "unit": "kW",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 2101282,
        "name": "Phase B active power",
        "custom_name": "Phase B Active Power",
        "unit": "kW",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 2101283,
        "name": "Phase C active power",
        "custom_name": "Phase C Active Power",
        "unit": "kW",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 2101600,
        "name": "iAcMeter",
        "custom_name": "iAcMeter",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
    },
    {
        "id": 2101601,
        "name": "iAcMeter",
        "custom_name": "iAcMeter IP",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
    },
    {
        "id": 2101602,
        "name": "Comm Status",
        "custom_name": "Comm Status",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
    },
    {
        "id": 2101605,
        "name": "iAcMeter",
        "custom_name": "iAcMeter Mode",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
    },
    {
        "id": 2101606,
        "name": "Meter Data Source",
        "custom_name": "Meter Data Source",
        "unit": None,
        "device_class": SensorDeviceClass.ENUM,
    },
]
