from homeassistant.components.sensor import SensorDeviceClass, SensorStateClass

CHARGING_PILE_SIGNALS = [
    {
        "id": 10001,
        "name": "Charging Connector No.",
        "custom_name": "Connector Number",
        "device_class": SensorDeviceClass.ENUM,
    },
    {
        "id": 10002,
        "name": "Charging Connector Type",
        "custom_name": "Connector Type",
        "device_class": SensorDeviceClass.ENUM,
    },
    {
        "id": 10003,
        "name": "Rated Output Power",
        "custom_name": "Rated Power",
        "unit": "kW",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 10004,
        "name": "Working Status",
        "custom_name": "Status",
        "device_class": SensorDeviceClass.ENUM,
    },
    {
        "id": 455780004,
        "name": "Output Relay Status",
        "custom_name": "Relay Status",
        "device_class": SensorDeviceClass.ENUM,
    },
    {
        "id": 455780005,
        "name": "Charging Connector Temperature",
        "custom_name": "Connector Temp",
        "unit": "°C",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 10032,
        "name": "A Output Current",
        "unit": "A",
        "custom_name": "Phase A Current",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 10033,
        "name": "C Output Current",
        "unit": "A",
        "custom_name": "Phase C Current",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 10034,
        "name": "B Output Current",
        "unit": "A",
        "custom_name": "Phase B Current",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 10013,
        "name": "Total Output Power",
        "unit": "kW",
        "custom_name": "Output Power",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 455780014,
        "name": "PWM Duty Cycle",
        "custom_name": "PWM Duty",
        "unit": "%",
        "device_class": SensorDeviceClass.POWER_FACTOR,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 10023,
        "name": "Lock Status",
        "custom_name": "Connector Lock",
        "device_class": SensorDeviceClass.ENUM,
    },
    {
        "id": 455780020,
        "name": "Reported Working Mode",
        "custom_name": "Working Mode",
        "device_class": SensorDeviceClass.ENUM,
    },
    {
        "id": 10029,
        "name": "Planned Departure Time",
        "custom_name": "Departure Time",
        "device_class": None,
    },
    {
        "id": 10030,
        "name": "Expected Charged Energy",
        "unit": "kWh",
        "custom_name": "Planned Charge Energy",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL,
    },
    {
        "id": 19999,
        "name": "Device connection status",
        "custom_name": "Connection Status",
        "device_class": SensorDeviceClass.ENUM,
    },
    {
        "id": 10036,
        "name": "Energy Charged",
        "unit": "s",
        "custom_name": "Charging Duration (s)",
        "device_class": SensorDeviceClass.DURATION,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
]

CHARGER_DEVICE_SIGNALS = [
    {
        "id": 10001,
        "name": "Software Version",
        "custom_name": "FW Version",
        "device_class": SensorDeviceClass.ENUM,
    },
    {
        "id": 10002,
        "name": "Hardware Version",
        "custom_name": "HW Version",
        "device_class": SensorDeviceClass.ENUM,
    },
    {
        "id": 455770003,
        "name": "ESN",
        "custom_name": "Serial Number",
        "device_class": None,
    },
    {
        "id": 10003,
        "name": "Rated Power",
        "unit": "kW",
        "custom_name": "Rated Power",
        "device_class": SensorDeviceClass.POWER,
    },
    {
        "id": 455770005,
        "name": "Phase A Voltage",
        "unit": "V",
        "custom_name": "Phase A Voltage",
        "device_class": SensorDeviceClass.VOLTAGE,
    },
    {
        "id": 455770006,
        "name": "Phase B Voltage",
        "unit": "V",
        "custom_name": "Phase B Voltage",
        "device_class": SensorDeviceClass.VOLTAGE,
    },
    {
        "id": 455770007,
        "name": "Phase C Voltage",
        "unit": "V",
        "custom_name": "Phase C Voltage",
        "device_class": SensorDeviceClass.VOLTAGE,
    },
    {
        "id": 10007,
        "name": "AC Charger Model",
        "custom_name": "Model",
        "device_class": SensorDeviceClass.ENUM,
    },
    {
        "id": 10008,
        "name": "Total Energy Charged",
        "unit": "kWh",
        "custom_name": "Total Energy",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "id": 455770010,
        "name": "AC Charger Temperature",
        "unit": "°C",
        "custom_name": "Charger Temp",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 10010,
        "name": "Charging Port Quantity",
        "custom_name": "Port Count",
        "device_class": SensorDeviceClass.ENUM,
    },
    {
        "id": 10012,
        "name": "Bluetooth name",
        "custom_name": "Bluetooth Name",
        "device_class": SensorDeviceClass.ENUM,
    },
    {
        "id": 19999,
        "name": "Device connection status",
        "custom_name": "Device Status",
        "device_class": SensorDeviceClass.ENUM,
    },
]
