from homeassistant.components.sensor import SensorDeviceClass, SensorStateClass

PLANT_SIGNALS = [
    {
        "key": "monthEnergy",
        "name": "Monthly Energy",
        "unit": "kWh",
        "meter_required": False,
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "key": "cumulativeEnergy",
        "name": "Total Energy",
        "unit": "kWh",
        "meter_required": False,
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "key": "dailyIncome",
        "name": "Today Income",
        "unit": "",
        "meter_required": False,
        "device_class": SensorDeviceClass.MONETARY,
        "state_class": SensorStateClass.TOTAL,
    },
    {
        "key": "dailyEnergy",
        "name": "Today Energy",
        "unit": "kWh",
        "meter_required": False,
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "key": "yearEnergy",
        "name": "Yearly Energy",
        "unit": "kWh",
        "meter_required": False,
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "key": "totalSelfUseEnergy",
        "name": "Self Used Energy Today",
        "unit": "kWh",
        "meter_required": True,
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "key": "dailyUseEnergy",
        "name": "Consumption Today",
        "unit": "kWh",
        "meter_required": True,
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "key": "pvSelfConsumptionEnergy",
        "name": "PV Self Consumption",
        "unit": "kWh",
        "meter_required": True,
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "key": "totalFeedInEnergy",
        "name": "PV Feed-In Energy",
        "unit": "kWh",
        "meter_required": True,
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "key": "totalGridImportEnergy",
        "name": "Imported Grid Energy",
        "unit": "kWh",
        "meter_required": True,
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "key": "totalConsumptionEnergy",
        "name": "Total Consumption",
        "unit": "kWh",
        "meter_required": True,
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "key": "gridImportRatio",
        "name": "Grid Import Ratio",
        "unit": "%",
        "meter_required": True,
        "device_class": SensorDeviceClass.POWER_FACTOR,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "key": "pvSelfConsumptionRatio",
        "name": "Self Consumption Ratio",
        "unit": "%",
        "meter_required": True,
        "device_class": SensorDeviceClass.POWER_FACTOR,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "key": "pvSelfConsumptionRatioByProduction",
        "name": "Self Consumption Ratio (by PV production)",
        "unit": "%",
        "meter_required": True,
        "device_class": SensorDeviceClass.POWER_FACTOR,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "key": "flow_solar_power",
        "name": "Flow Solar Power",
        "unit": "kW",
        "meter_required": False,
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "key": "flow_battery_power",
        "name": "Flow Battery Power",
        "unit": "kW",
        "meter_required": False,
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "key": "flow_load_power",
        "name": "Flow Load Power",
        "unit": "kW",
        "meter_required": False,
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "key": "flow_grid_power",
        "name": "Flow Buy Power",
        "unit": "kW",
        "meter_required": False,
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
]
