version: 4
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto:1883
  user: addons
  password: cee4Aibau0ohshah0Eegiey1cuChusaeb6xophuV9oofulied8aighohxeinoh0a
serial:
  port: >-
    /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230505150534-if00
  adapter: ezsp
  baudrate: 115200
  rtscts: false
advanced:
  log_level: info
  channel: 25
  network_key:
    - 52
    - 50
    - 128
    - 240
    - 139
    - 157
    - 119
    - 5
    - 195
    - 200
    - 147
    - 221
    - 119
    - 175
    - 175
    - 143
  pan_id: 23337
  ext_pan_id:
    - 38
    - 145
    - 196
    - 172
    - 48
    - 1
    - 147
    - 146
frontend:
  enabled: true
  port: 8099
homeassistant:
  enabled: true
onboarding: false
